
##FORT SMITH ANALYSES AND GRAPHING##

```{r}
library(png)
library(reticulate)
library(IHA)
library(tidyverse)
library(dplyr)
library(tidyhydat)
library(zoo)
library(lubridate)
library(ggplot2)
library(sf)
library(mapview)
```

Tidying Functions
```{r}

flow_data_predam_FS <- function(df,Date, Value) {
library(dplyr)
df <- df %>%
  select(Date, Value) %>%
  na.omit()%>%
  filter(Date < "1966-10-01" & Date >= "1959-10-01") %>% 
  mutate(Date = format(Date,"%d-%m-%Y"))
  return(df)
}


flow_data_postdam <- function(df,Date, Value) {
library(dplyr)
df <- df %>%
  select(Date, Value) %>%
  na.omit() %>%
  filter(Date >= "1968-10-01" & Date < "1991-10-01") %>%
  mutate(Date = format(Date,"%d-%m-%Y"))
  return(df)
}



```

#Get the flow data for Station #07NB001
```{r}
Fort_Smith_Flows <- tidyhydat::hy_daily_flows(station_number = "07NB001")
```

#Get the latitude and longitude coordinates for Station #07NB001
```{r}
latlong_07NB001 <- hy_stations(station_number= "07NB001" ) %>% select(LATITUDE, LONGITUDE)
```

#Map the station
```{r}
sdf <- st_as_sf(latlong_07NB001, coords = c("LONGITUDE", "LATITUDE"),  crs = 4326)
mapview(sdf, map.types = "CartoDB.Positron")

```


#Separate the data into pre and post dam stations 
```{r}

FL_FS_predam <- flow_data_predam_FS(Fort_Smith_Flows) 

FL_FS_postdam <- flow_data_postdam(Fort_Smith_Flows)

```

IHA ANALYSES
Predam Period 1953-1966

```{r}

## Convert data to zoo object to prep for IHA analyses

flow_data <- zoo(FL_FS_predam$Value, order.by = as.Date(as.character(FL_FS_predam$Date), format = "%d-%m-%Y"))

## Run IHA analyses
group1_output <- group1(flow_data, year = "water", FUN = median)
group2_output <- group2(flow_data, year = "water", mimic.tnc = TRUE)
group3_output <- group3(flow_data, year = "water", mimic.tnc = FALSE)
group4_output <- group4(flow_data, year = "water")
group5_output <- group5(flow_data, year = "water")

## Convert outputs
group1_output <- as.data.frame(group1_output)
group2_output <- group2_output[,-1]
group3_output <- as.data.frame(group3_output)
group4_output <- as.data.frame(group4_output)
group5_output <- as.data.frame(group5_output)

#deleting last years because it has an extra year not in the data
group1_output <- group1_output[-15,]
group2_output <- group2_output[-15,]
group3_output <- group3_output[-15,]
group4_output <- group4_output[-15,]
group5_output <- group5_output[-15,]

## Create output dataframe 
IHA_output <- bind_cols(list(group1_output, group2_output, group3_output, group4_output, group5_output))

library(tibble)
IHA_output_predam <- tibble::rownames_to_column(IHA_output, "Year") %>%
  add_row(Year = c("1968", "1967") )%>%
  add_column(Time_Period = "Pre Dam" )

```


##IHA ANALYSES ##
#Postdam Period 1969-1991## 

```{r}
## Convert data to zoo object to prep for IHA analyses

flow_data <- zoo(FL_FS_postdam$Value, order.by = as.Date(as.character(FL_FS_postdam$Date), format = "%d-%m-%Y"))

## Run IHA analyses
group1_output <- group1(flow_data, year = "water", FUN = median)
group2_output <- group2(flow_data, year = "water", mimic.tnc = TRUE)
group3_output <- group3(flow_data, year = "water", mimic.tnc = FALSE)
group4_output <- group4(flow_data, year = "water")
group5_output <- group5(flow_data, year = "water")

## Convert outputs
group1_output <- as.data.frame(group1_output)
group2_output <- group2_output[,-1]
group3_output <- as.data.frame(group3_output)
group4_output <- as.data.frame(group4_output)
group5_output <- as.data.frame(group5_output)

#deleting last years because it has an extra year not in the data

## Create output dataframe 
IHA_output <- bind_cols(list(group1_output, group2_output, group3_output, group4_output, group5_output))

library(tibble)
IHA_output_postdam <- tibble::rownames_to_column(IHA_output, "Year") %>%
  add_column(Time_Period = "Post Dam" )
```

#Join the two dataframes into one##

```{r}

IHA_both <- rbind(IHA_output_predam, IHA_output_postdam) %>%
  add_row(Year = c("1968", "1967") ) 

```

#Graphing the IHA Variables 

```{r}

dontgraph <- c("Year", "Time_Period")

for (col in names(IHA_both)[!names(IHA_both) %in% dontgraph]) {
  print(ggplot(data = IHA_both, aes(x = Year, y = IHA_both[,col], group = 1 )) +
          geom_line(aes(colour = Time_Period) ) +
      geom_point(aes(colour = Time_Period)) +
  ggtitle(col)  +
    ylab(col) +
  theme_bw() +
    theme(plot.title =  element_text(size = 10, hjust = .5, face = "bold")) +
     theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
    theme(legend.background = element_rect(colour = 'black', fill = 'white', linetype='solid')) +
  theme(legend.position=c(0.87, 0.8), legend.title=element_text(size=8), legend.text=element_text(size=7)) ) 
  }

```


```{r}



```


```{r}




```

